### ISSUE TITLE
Crash CoreGraphics CGClipStackCreateMutable

### ISSUE THREAD

**Issue by hellais** [ooni/probe-ios#227] opened 2019-01-17 21:31 UTC
This affects 3 users and is fabric `#73`.

This smells like an iOS bug to be honest.

```
Crashed: com.apple.main-thread
0  libsystem_malloc.dylib         0x18aa64da8 nanov2_allocate_from_block$VARIANT$armv81 + 528
1  libsystem_malloc.dylib         0x18aa64040 nanov2_allocate$VARIANT$armv81 + 140
2  libsystem_malloc.dylib         0x18aa63f64 nanov2_malloc$VARIANT$armv81 + 60
3  libsystem_malloc.dylib         0x18aa719a0 malloc_zone_malloc + 156
4  libsystem_malloc.dylib         0x18aa723b0 malloc + 32
5  CoreGraphics                   0x18cdb219c CGClipStackCreateMutable + 40
6  CoreGraphics                   0x18cb72d00 CGGStateClipReset + 28
7  CoreGraphics                   0x18cd30d1c CGGStateCreate + 68
8  CoreGraphics                   0x18ccbaa5c CGGStackGetGState + 28
9  CoreGraphics                   0x18cca3a18 CGContextCreateWithDelegateAndInfo + 180
10 QuartzCore                     0x18f4ab0c4 CACGContextEvaluator::CACGContextEvaluator(unsigned long, unsigned long, CGColorSpace*) + 140
11 QuartzCore                     0x18f372b54 CABackingStoreUpdate_ + 144
12 QuartzCore                     0x18f498284 invocation function for block in CA::Layer::display_() + 52
13 QuartzCore                     0x18f490fbc -[CALayer _display] + 1540
14 QuartzCore                     0x18f3f551c CA::Context::commit_transaction(CA::Transaction*) + 548
15 QuartzCore                     0x18f423d7c CA::Transaction::commit() + 608
16 UIKitCore                      0x1b805c578 <redacted> + 172
17 UIKitCore                      0x1b814fc68 <redacted> + 5516
18 UIKitCore                      0x1b8148450 <redacted> + 152
19 CoreFoundation                 0x18ae251f0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
20 CoreFoundation                 0x18ae25170 __CFRunLoopDoSource0 + 88
21 CoreFoundation                 0x18ae24a54 __CFRunLoopDoSources0 + 176
22 CoreFoundation                 0x18ae1f920 __CFRunLoopRun + 1040
23 CoreFoundation                 0x18ae1f1f0 CFRunLoopRunSpecific + 436
24 GraphicsServices               0x18d098584 GSEventRunModal + 100
25 UIKitCore                      0x1b8062d40 UIApplicationMain + 212
26 ooniprobe                      0x102c16fc8 main (main.m:6)
27 libdyld.dylib                  0x18a8debb4 start + 4
```

**Comment by bassosimone** [comment] 2019-06-07 17:59
This is IMHO also caused by the memory corruption at https://github.com/measurement-kit/measurement-kit/issues/1739. Closing unless we see a relapse. (Most bugs that we did see were indeed caused by this unique corruption event and were random because of the corruption.)

**Closed by bassosimone** 2019-06-07 17:59 UTC
Labels: bug, cannot reproduce bug, low priority
