### ISSUE TITLE
icons misplaced when returning from settings menus

### ISSUE THREAD

**Issue by willscott** [ooni/probe-ios#191] opened 2018-11-19 14:27 UTC
On latest iOS. iPhone 7

When clicking into notifications / sharing / advanced / about OONI in the settings menu, and hitting the "<" arrow in the upper left to return to the main settings list, the 3 icons in the bottom of the screen are displayed too high during the transition, and without their labels.

**Comment by hellais** [comment] 2018-11-19 14:34
Can you share a screenshot of the problem?

I am not able to reproduce this on 12.0.1 (latest is 12.1.0) on an iPhone 6s.

**Comment by willscott** [comment] 2018-11-19 14:38
<img width="618" alt="screen shot 2018-11-19 at 6 38 04 am" src="https://user-images.githubusercontent.com/428199/48713633-b60a1980-ebc5-11e8-836a-b2b9e9e4bd64.png">

**Comment by lorenzoPrimi** [comment] 2018-12-04 13:10
The tab bar is standard and not managed by any custom class.
I'm doing some researches and seems like an iOS bug, will try some hacks

**Comment by lorenzoPrimi** [comment] 2018-12-04 22:33
This happens due to the tab bar being translucent, to fix it I should remove this effect.
@elioqoshi any opinion?

![translucent](https://user-images.githubusercontent.com/1616097/49477371-7e24e800-f7fb-11e8-8d94-5026344b76a9.png)
![not_translucent](https://user-images.githubusercontent.com/1616097/49477356-72392600-f7fb-11e8-886f-60c73e3ca7d5.png)

**Comment by lorenzoPrimi** [comment] 2018-12-04 22:35
"This has been solved in the new iOS 12.1.1 (currently released as a beta version)"
cit from stackoverflow

**Comment by lorenzoPrimi** [comment] 2018-12-05 10:39
It's a confirmed iOS bug, happens in many other app I have since I updated iOS

**Comment by lorenzoPrimi** [comment] 2018-12-11 12:17
Closing as it's an iOS bug it affects praticaly every app.

**Closed by lorenzoPrimi** 2018-12-11 12:17 UTC
